# .readthedocs.yaml
version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.11"
  jobs:
    pre_install:
      - pip install uv  # Install uv *before* installing project dependencies
    post_install:
      - uv venv # Create venv using uv
      - uv pip install .[docs] #Install project dependencies
sphinx:
  configuration: docs/source/conf.py
  builder: html
  fail_on_warning: true