# .readthedocs.yaml
version: 2

build:
os: ubuntu-22.04
tools:
    python: "3.11"  # Or your desired Python version

sphinx:
configuration: docs/source/conf.py
builder: html

python:
    install:
    - method: pip  # Explicitly use pip (even though we're using pyproject.toml)
    extra_requirements:
        - docs  # Install the "docs" optional dependency group